apiVersion: v1
kind: ConfigMap
data:
  nginx.conf: |
    events {
    }

    http {
      server {
        listen 8000;
        root /data/www;
        location / {
          try_files '' /redirect.html =404;
        }
      }
    }
  redirect.html: |
    <head>
      <meta http-equiv="Refresh" content="0; URL=https://VMware.zoom.us/j/7924368104">
    </head>
    <body>
      <a href="https://VMware.zoom.us/j/7924368104">https://VMware.zoom.us/j/7924368104</a>
    </body>
metadata:
  name: nginx-conf
