postgresql:
  enabled: false

concourse:
  image: concourse/concourse
  imageTag: "7.2.0"
  # imageDigest: sha256:bd615c69261179fe99aa39640c2f28c550e8306e025641489485effce65e7f6a

  secrets:
    teamAuthorizedKeys:
    - team: diego
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPVX0dq1paSLmoLH8kJCu2XswVyYkyJUXNtncxM2R/sQwgrAK+LIDkKMU1vBkHK8HtuFZnutU6ZU3RD1Zmnwdnn01TP1fgeAJOEYfTi0lgyAwq5466MqFY1OVHg8ueOS54ejNU3k+Hw58Hy0W9FNZb3KshieOdqSlyvIzjoL2WQSOEZIZkh0ZihOAVaVvPITonFpfKI8VIwmbBiQAR0RhZwd8aF0tVpNjt45yVxREDgAhaPowqsoZjMGvFDkKFfLB6y0OVmhgKjCYQXlGJwQU9u2k0L5EImpX/40ZPW7wj20en5DRprizzqzo94aoDO6gpg/PZJnedB2NHzTLL373V'
    - team: toolsmiths
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXHxnupNtmDSiVtMsABr9I2Bt48MTbOazBzUr0+VMEYq4sPuEG4pVUnzrGr57UmYpDdDl/o+G7l7pws9DV3aUmcXZuWkP3ujRXefeNO7srumy60AqGK6Wor+L97b55vjPXsQz6YwrblAmgMuIN2MO2c8gijR6a0/yzSG4FLv+4njeK4XI62mgNtkF536Ms+9zyekcTkR0BeO4mg4ebicM5KTIyjzkpCe6S/Sjccaxpl1OkcQ9291TTFFGz6IZbtgF/CwmdJIEudWvSEwRLZOVqSW2PEuQ98MHk+KIQcze/GJszAmhBa9HfaYcf5vt+yR8e+KIxMeZASNlZge9t0p//'
    - team: cf-uaa
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCuUbLF+OkKol0uq88SdjAQBzStXmD+/Tl4iMtPstQN7bvlUbfdiMsR0optlbo1SJjTNWXTZlKeuFjucRtyWi/uHCGojlhtthE35lzVCTCSYp7pbUPRdTX0rSeogu8nPzBRudRl7bCzxuGxehw+yg3xTmKnKE4g4U0fvRFnb4lwjW0C+Erfl2ffov99nYhbp7fVXp9l7TZJJzEx0Xe2V+dgwnnfwYPw4WGs/Nii7uCLLepHowmxvL5OBEag0Yd4HofXZtJxydHQKmpzjzW2hv0paR351JrJrNjIvsTNnSSV94njZJXYH+YBBmyjM1ntaCnuw9wxWDSfcESlBjiRE85l'
    - team: cf-uaa-pivotal-only
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCc+hgsQC/6sYdUyFx0rA0bFv9T985d4/CU3QlAk3F+MG6VjL2wJGvg4sPljE0kqZCkgSUgFM/rd0wuSzNcToWrvfhcceEOvTzNO5SuIYjNqkyOEMI1d0lKjpy4w/9VqtP9bqEi3TSv+lkwvlsnb+Xb05O4IgVuDU1wrjjQPPQgJkizxsH590M3GxZiG1iyj2qYEFGIJoEQAIW1hvK+yKSUFTpeO+4W/z9gLPK6cMreKMzo1DUhqC4amgBIo3g1/bltSUC5dyFtmvvSb/j6+qP4mHBOBs0eXS8ZLHREOmK8wBIlDg3S28RVKDsmmtcFM9UrBswj3BRpC6Os4BXD/QDN'
    - team: windows-containers
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDE9Zp5Jk1/lXI9gglhBd6bybkt5cgCYl4KktTT8XMuMoEI5pkdV3jewfg8PwD5HLHDcUSbjOeLEHXZn4eKckcodv9SshL8HMbUjnoVKmUEQpa/+LY8+DBHAX/WuZu8XJyv5479PgzxZRg0YW43KhEa7Jj910+OnLLLo0vnGaNDbHfN6N9jZ34O7TEzKipMV7wOBf7opsYqqJhWHXeSqEy+DHK2q+cswtBcrngInZ44tL3w9PvZwkKDuX8p4zmBfEMmCQqd+4FCAgiZZi5cMCrVkyr3iSEiLCFi2EN7Uojw+CdvC8LDESr7DMAgrjtJ1VERJvjn80M4x+IbgbtoSkFP'
    - team: telemetry-and-insights
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5eCEYB9os8sjARt2UgpDNtY9CLKB6xUZ6LfLWGWCkxf98zxeqhB8L1n2Tu/hEZha+Btf7HD15fyLgmljhSDuqIrn0I8mS1Ulk5ohk0Ofo939OTCFlJIKxy6S4DhIEkK2XOIsw2mSrEL3omxEsT2iBopwJq/b/3Ikdyr66JbESygy4Zk5CJJ6Mw6JRxJFd0BUlAHcV2a+/aCbxNPOnZUbVNfBjGh/pka0m6DHnuGxY9fhY8PZhCalSpeiyytSFWs+6d30WgepIiS1XGVsgT3t/dott8/1T60wqJLDyoxgkincC7gBH/H3/rdXnxuHe1xQThYhwOSdlAom9KIKvKQlF'
    - team: cf-volume-services
      key: |-
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDaYvKmhyM49CK0bd0Bz/z8XL/DnbsWkh/1LGAnaQrMGstfKkqkcQnKfoYTu5VtBIzrmDWdy5CjAiAhyfE4ko8Kd/gUByO4DlH5E4FQKRhsILX6wcXatI56nCO1X46jQTGAcouA+/IrDMG1cjVtRhgItOj0ZxNN+Y8e1X1EkTHeH+bhw80GOIbqSTLztGBnETu7Y031rIsCEgp5P3cKvjbJovszC9yKRrVAEFtXdd5IggQ2Cu/YE/9A5IbFI1DSLgOo8I0gTlJu5nuCJ2W4UFbWE1Cq3W68h4SMzalJB4xah5IUrniQ8oQgVZYsA1NLKRe82PBwM4L8toJoLiQtJ22BmJz7ihw6Uukdm/4MmamHcBzYmYOl8IT40ZSzTdAaMXBTrEdJOtEYitXniT6HPPH9WC7U8zRGv2rCl3g7FsvANSx2cc88Rz0hJXaC9zD6Ad4TWJf2E4m0DBvj1OAm19UmcExLGR+g2cRRwwU/w7cGA4fro3vbzuiGaSnVnh/CKNUQ3MdRJJWv504NqzxLfC6q7zTftgplJp92w2TDb6bgupgshLcMta5ptpFazb8emGfdfTluYoZxa+nh3zRMAL9LtuxOia5M7ee3jF/NQgogyN6oPZgiFGYOt3Zqwh3iYbLvUkJPgpd50BWVOZdtBgOwrgX6f/5eZpAqaGNycYqccQ==
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDV1A/gb0tTceKynSBDums8HeCxlZ3sTjL7jLnn+WDIv7Cy9/sTFAR5zS8luV/aV7W3D5GOlleqcotGe+ju9d3NUXwmBlx3dC97U+dc0zT8Z56nAn+eokMwyuyGrh1BaFrGxtezZ0nGhlf9jYXVS8glc1ZxcAxY4nOBIApqap/t4Ya4j5cwxCQPzM/aR8N8EQoSInF0g9F3y2Rsae4mkrcl8oSRt1neZ5SCHYd+nEFdoqAIeZWoDIyyx6Acm//jJrjSD7roYmVymnxLpRWc+NkiSOZW2SLm8WIk40JWOL7uITWVAHEMSmvJO8d1J1Tbmtcf5QW68ncB6AyI9DJ/8xJ4tgI1toQwifDLWwo1wFaH8pxTvGnKYmL9G3rjMVBpntagzzyv6ZeasQUPpAIGGszG5drAC9+z3vdGnaAYyOIkWrQk2X7ebjXE+BP/0Bs9xlfo6AxTCKlc7cG8mMJ4tKY6NhP8E2tC+dNG6kcbZ5ir5aimpvUDYGASG6F+uaUhwSU= lisaburns@lisaburns-a01.vmware.com
    - team: tanzu-user-auth
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDA1pzjdewJ06jWXSPzgw3VzZvJBBHaUwFTVH5pU03n1LdQSP7IwIDFZirp2r8qnXN1Art4zxnzjdQxazS5AGvjIo/c3h5TYDz/wcToIvLsKvBIOJSlQgY3W+8UONA6wLr2rdI7sO+J1REzkZhgaYWVLRw1xfpyYjIjU1egy2bGlYM33TtCFqnw7Ptz1gFDVfuyzsIV2QR7J43oZmNcLX5BnPOCV94SyOYZxoyemhLe8XZg0yIth9vGXX9Cno2s6iFAIwmbzRnduCx69e2ADssAicG4nol7aqFHr37hW+Ck1nlhTKmpcYvuvfpD71sX7L6ZuR5O7tSioS/rlXbMh9/uDXzGoI5Q0vq5k4SifWzIYS/rcfDHp+TR4TJfFknT3MXqxhahVVldL7UDYB2xu9qzs4YSKkpmW9X49ihLSKT5Tx2bijxqqacaaOxZPk9aJrQHbhhB7INZAeGWXtPWmWBNJP5lod1/j4KcQ4mKoEbun7tj/dfgSOfv+kNyskCUEyBpkbu69L6Btv00+bFheiP13Cpq9CxraNCHJRBwtcdVbKiaVBEUOp1qwiOTgDu4ySlmiSy6kXcXVilM+hL84zNESkPwejoB5WvNSqkD0w5k+v+AlM8uegN7UwEgC6GjlKx8QgSWIdvx8w4m4IoLtrS88Qi//Udm3utbiLHn8OLurQ=='
    - team: platformservices
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYRce9Aci/Pk5pNr2N7UWYP3ROYWKoabQFgprwIsXGuis18j3XzaJV2Z52S3va7dtSbGoLKvpBIGtF3ItUuxHchz30Bdq2bkBIzO2qCg8QoNWADdR+syeePVRmExmaRjskEKOg/P6xcValg7ypnuGrxiQW1qhxCL0nvvURn2hyeXP6XMuJQ4Nu34gRzixJx1Ije/e7cHeLBySIebKa42wkYkkbAJEUB9/RJhYBeTBsTczEvNibjLsu3lLpgsumsnpGgGkpfjOESWeofiKEffpNfKmayzIA9d1TRFcVCfGdIyVNMXObisd1PB0UOOFmBoUocGZGHPj7imqlSzxOyd0D'
    - team: pcf-app-sso
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3KGWt2A4gguTpsMcdKJ0ttUhIl35+3L5bRMn/ITICF1mHlN72H1YlrckuoEq7e2WKQaokuKCrAzNxS/HOcSh50SRzCzNN+4IhUghiBo/PZS+M8N7J2EvEMaSEpY+sM35BQTOufZ0K7dlc/u8tVXTZ/zVTjSg0om5GLQqPkVqzMJsk+H803enPN3xDZkqe1Mk6gO+oiTDewIw5ZRKLahl11+wFmuvaw0b4kHSjVHeC2AMnXQPYoZ3fcMFvzOmGjGpcYeudGzYdBgorPYeP3KwfJb+qNL7lluFg/EwFncWYC2UVH8FXu9DN+XEavhCHtZZDdOubX5SMbhMUeVRBt9/oruV2J6xiTMtYjduS0GJD8mxrXH0tpdJ88kltqWwiG4tf+g0rsmbF10oFtg+htQeZkYZg1oFzuLSyy/0IvaGNPxwpTX4SwTzmsxwxNI7mrFa3qfNmdOjx7Ap8aiezT7koBVvl7wIa6XWjD7n9FKXgSx2nUJ5So9vLrUPU+ZylHEc='
    - team: pcf-rabbitmq
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOcOjNDYyomRfNuVgRVreR2PrsfOqkq5HGKmq5lq425rSHuk9F8/nVW5fN4A+kOHCs/mrGr5CRbKz7RsYT9BYVCXUywMrJOjHcUhfDK92oTQ7SztFge7Le0xgMgQrHD09LUPI4u3TXUIWYZzxCl+srAou5rLCY3+x0c/bKPjmYTZC4P2cBC6apoMQsqdCeSMTLyVrk8THjEsOCs+mU98hkmGBPfNLuaqbmnmSWULhsjgCmhojoSEsSXik7oztgNYkTtuY53ZUlFzckE5INCu7w/p/m8XsYSnwozSFpDxwCYf126K5BiglKrr5qHVvMeMY0McaBVFLUfMd/PqWcV0SD'

  postgresql:
    enabled: false

  worker:
    enabled: false

  web:
    annotations:
      rollingUpdate: "3"
    replicas: 2
    env:
    - name: CONCOURSE_TRACING_JAEGER_ENDPOINT
      value: http://127.0.0.1:14268/api/traces
    - name: CONCOURSE_TRACING_JAEGER_SERVICE
      value: web
      # # The OTLP tracing stuff aren't on the latest chart yet so we're stting them as env vars
    # - name: CONCOURSE_TRACING_SERVICE_NAME
      # value: web
    # - name: CONCOURSE_TRACING_OTLP_ADDRESS
      # value: 127.0.0.1:55680
    # - name: CONCOURSE_TRACING_OTLP_USE_TLS
      # value: "false"
    nodeSelector: { cloud.google.com/gke-nodepool: generic-1 }
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: hush-house-web
                release: hush-house
    # NOTE: If you add sidecars make sure you set resources to maintain the QoS class of "guaranteed"
    sidecarContainers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.15.0
        args: ['--config=/etc/config/otelcol.yml']
        resources:
          limits:
            memory: 100Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 500m
        volumeMounts:
          - name: otelcol-config
            mountPath: /etc/config
      - name: prom-storage-adapter
        image: wavefronthq/prometheus-storage-adapter
        resources:
          limits:
            memory: 100Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 500m
        args:
          - -proxy=127.0.0.1
          - -proxy-port=2878
          - -listen=9000
          - -convert-paths=true
      - name: wavefront-proxy
        image: wavefronthq/proxy:9.2
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
          requests:
            memory: 500Mi
            cpu: 500m
        env:
        - name: WAVEFRONT_URL
          value: "https://vmware.wavefront.com/api/"
        - name: WAVEFRONT_PROXY_ARGS
          # https://github.com/wavefrontHQ/wavefront-proxy/blob/master/pkg/etc/wavefront/wavefront-proxy/wavefront.conf.default
          value: |
            --prefix concourse
            --hostname=hush-house.pivotal.io
            --traceJaegerGrpcListenerPorts 14250
            --traceJaegerApplicationName Concourse
        - name: WAVEFRONT_TOKEN
          valueFrom:
            secretKeyRef:
              name: wavefront-proxy
              key: token
    additionalVolumes:
      - name: otelcol-config
        configMap:
          name: otelcol-config
    service:
      api:
        type: LoadBalancer
        loadBalancerIP: 35.202.234.135
      workerGateway:
        type: LoadBalancer
        loadBalancerIP: 35.202.234.135
    resources:
      requests:
        cpu: 5000m
        memory: 2Gi
      limits:
        cpu: 5000m
        memory: 6Gi
    strategy:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1

  concourse:
    web:
      auth:
        mainTeam:
          localUser: admin
          github:
            team: concourse:maintainers
        github:
          enabled: true
      bindPort: 80
      clusterName: hush-house
      containerPlacementStrategy: random
      defaultDaysToRetainBuildLogs: 30
      enableLidar: true
      enableBuildAuditing: true
      enableContainerAuditing: true
      enableGlobalResources: true
      enableJobAuditing: true
      enablePipelineAuditing: true
      enableResourceAuditing: true
      enableSystemAuditing: true
      enableTeamAuditing: true
      enableVolumeAuditing: true
      enableWorkerAuditing: true
      baggageclaimResponseHeaderTimeout: 10m
      encryption: { enabled: true }
      externalUrl: https://hush-house.pivotal.io
      kubernetes: { keepNamespaces: true }
      metrics:
        attribute: "environment:hush-house"
      letsEncrypt: { enabled: true, acmeURL: "https://acme-v02.api.letsencrypt.org/directory" }
      tls: { enabled: true, bindPort: 443 }
      prometheus:
        enabled: true
      # datadog:
      #   enabled: true

      #   # horrible hack; we need a proper way to configure unix sockets
      #   agentHost: unix
      #   agentPort: ///var/run/datadog/dsd.socket
      postgres:
        host: 173.255.117.168
        database: atc
        sslmode: verify-ca
      logLevel: debug
    tsa:
      logLevel: debug
