postgresql:
  enabled: false

concourse:
  image: concourse/concourse-rc
  imageDigest: sha256:fa136abb336f2c2aed8d41d21b382d364c3387c24f3fdef15c720c292c9216d4

  postgresql:
    enabled: false

  web:
    enabled: false

  persistence:
    worker:
      storageClass: ssd
      size: 750Gi

  worker:
    replicas: 3
    terminationGracePeriodSeconds: 3600
    livenessProbe:
      periodSeconds: 60
      failureThreshold: 10
      timeoutSeconds: 45
    nodeSelector: { cloud.google.com/gke-nodepool: ci-workers-pr }
    hardAntiAffinity: true
    resources:
      limits:   { cpu: 7500m, memory: 14Gi }
      requests: { cpu: 0m,    memory: 0Gi  }

  concourse:
    worker:
      rebalanceInterval: 2h
      baggageclaim: { driver: overlay }
      tag: "pr"
      healthcheckTimeout: 40s
      tsa:
        hosts: ['ci-web-worker-gateway.ci.svc.cluster.local:2222']
      runtime: containerd
      containerd:
        networkPool: "10.254.0.0/16"
        maxContainers: "500"
        restrictedNetworks:
          - "169.254.169.254/32"
